var n = 1455;
var f = 3.14;
var nn = Number('45.455');
console.log(nn);
console.log(Number.parseInt(nn));
console.log(Number.MAX_VALUE);
console.log(Number.MIN_VALUE);
console.log(Number.MIN_SAFE_INTEGER);
console.log(1/0);
console.log('abc'*10);